apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: bitnami/bitnami-shell
          name: app
          command:
          - /bin/bash
          - -c
          args:
          - sleep 360
          env:
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-x-secret
                  key: key.pem
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 512Mi
              cpu: 20m
